IF DB_ID('PHANMEMTHITN') IS NULL CREATE DATABASE [PHANMEMTHITN]
GO

USE PHANMEMTHITN
GO

CREATE TABLE SINHVIEN
(
	STT INT IDENTITY (1,1),
	MASV VARCHAR(15) PRIMARY KEY,
	LOP VARCHAR(10) NOT NULL,
	TENSV NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
)
GO

CREATE TABLE GIANGVIEN 
(
	STT INT IDENTITY(1,1),
	MAGV VARCHAR(15) PRIMARY KEY ,
	TENGV NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	MATKHAU VARCHAR(20) NOT NULL
)
GO

CREATE TABLE QUANTRI
(
	STT INT IDENTITY(1,1),
	TENTK VARCHAR(15) PRIMARY KEY,
	MATKHAU NVARCHAR(20) NOT NULL,
)
GO

CREATE TABLE MONTHI
(
	STT INT IDENTITY(1,1),
	MAMT VARCHAR(10) PRIMARY KEY,
	TENMT NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE DANHMUCCAUHOI
(
	STT INT IDENTITY(1,1),
	MADANHMUC VARCHAR(10) PRIMARY KEY,
	TENDM NVARCHAR(50) NOT NULL,
	MAMT VARCHAR(10) FOREIGN KEY REFERENCES MONTHI(MAMT) ON UPDATE CASCADE
)
GO


CREATE TABLE CAUHOI
(
	STT INT IDENTITY(1,1) NOT NULL,
	MACAUHOI VARCHAR(10) PRIMARY KEY,
	DOKHO INT NOT NULL,
	NDCAUHOI NVARCHAR(500),
	DAPAN1 NVARCHAR NOT NULL, 
	DAPAN2 NVARCHAR NOT NULL,	
	DAPAN3 NVARCHAR NOT NULL,
	DAPAN4 NVARCHAR NOT NULL,
	DAPANDUNG NVARCHAR NOT NULL,
	MADANHMUC VARCHAR(10) FOREIGN KEY REFERENCES DANHMUCCAUHOI(MADANHMUC) ON UPDATE CASCADE
)
GO

CREATE TABLE KITHI
(
	ID INT IDENTITY(1,1),
	MAKITHI VARCHAR(10) PRIMARY KEY,
	TENKITHI NVARCHAR(50)
)
GO

CREATE TABLE DETHI
(
	ID INT IDENTITY(1,1),
	MADETHI VARCHAR(10) PRIMARY KEY,
	MAKITHI VARCHAR(10) FOREIGN KEY REFERENCES KITHI(MAKITHI) ON UPDATE CASCADE,
	MACAUHOI VARCHAR(10) FOREIGN KEY REFERENCES CAUHOI(MACAUHOI) ON UPDATE CASCADE
)
GO

CREATE TABLE BANGDIEM
(
	ID INT IDENTITY(1,1),
	MABD VARCHAR(10) PRIMARY KEY,
	MADETHI VARCHAR(10) FOREIGN KEY REFERENCES DETHI(MADETHI) ON UPDATE CASCADE,
	DIEM FLOAT
)
GO
